apiVersion: v1
kind: Service
metadata:
  name: autodeploy-monitor-service
spec:
  selector:
    app: autodeploy-monitor
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
